branch-defaults:
  master:
    environment: Bloggy-env
environment-defaults:
  Bloggy-env:
    branch: master
    repository: bloggy-repo
global:
  application_name: bloggy
  default_ec2_keyname: blog-key
  default_platform: arn:aws:elasticbeanstalk:ap-southeast-2::platform/PHP 7.0 running
    on 64bit Amazon Linux/2.4.1
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
