branch-defaults:
  master:
    environment: Bloggy-env
environment-defaults:
  Bloggy-env:
    branch: null
    repository: null
global:
  application_name: bloggy
  default_ec2_keyname: blog-key
  default_platform: PHP 7.0
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
